import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import NextAuthProvider from "@/components/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uvumi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="flex flex-row">
            <div className="w-[18rem] md:block hidden">
              <Sidebar />
            </div>
            <div className="bg-teal-100 flex-1">{children}</div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
